export const VALID_ZIP_WITH_RESULTS = '90210';
export const VALID_ZIP_NO_RESULTS = '89412';
export const ZIP_NO_NEARBY = '00001';
export const INVALID_ZIP = '99999';
export const INVALID_ZIP_LENGTH = '1234';
export const NEARBY_ZIP1 = '90209';
export const NEARBY_ZIP2 = '90213';
export const ZIP_REJECTS = '00002';
export const FDIC_REJECTS = '00003';
export const MULTIPLE_ZIPS = [
  VALID_ZIP_WITH_RESULTS,
  VALID_ZIP_NO_RESULTS,
  INVALID_ZIP,
  FDIC_REJECTS,
];
export const ALL_ZIPS_NO_RESULTS = [VALID_ZIP_NO_RESULTS, VALID_ZIP_NO_RESULTS];
export const ALL_ZIPS_REJECT = [FDIC_REJECTS, FDIC_REJECTS, FDIC_REJECTS];
